spring:
  application:
    name: sgr
  datasource:
    url: jdbc:mysql://localhost:3306/MySGR?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi

    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/MySGR?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi&useUnicode=true&characterEncoding=utf8
    username: alphonceSGR
    password: Rita@123#


    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: MySGR-HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        connection:
          useUnicode: true
          characterEncoding: utf8
          charSet: utf8




# (Optional) logging SQL query parameters
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
